//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDCibertecAppWebApiRest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EventoDeportivoCibertecEntities : DbContext
    {
        public EventoDeportivoCibertecEntities()
            : base("name=EventoDeportivoCibertecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sede> sede { get; set; }
        public virtual DbSet<tb_categoria> tb_categoria { get; set; }
        public virtual DbSet<tb_Club> tb_Club { get; set; }
        public virtual DbSet<tb_comprobante_pago> tb_comprobante_pago { get; set; }
        public virtual DbSet<tb_detalle_modalidad> tb_detalle_modalidad { get; set; }
        public virtual DbSet<tb_detalle_participante> tb_detalle_participante { get; set; }
        public virtual DbSet<tb_disciplina> tb_disciplina { get; set; }
        public virtual DbSet<tb_equipo> tb_equipo { get; set; }
        public virtual DbSet<tb_evento> tb_evento { get; set; }
        public virtual DbSet<tb_ficha_inscripcion> tb_ficha_inscripcion { get; set; }
        public virtual DbSet<tb_menu> tb_menu { get; set; }
        public virtual DbSet<tb_modalidad> tb_modalidad { get; set; }
        public virtual DbSet<tb_participante> tb_participante { get; set; }
        public virtual DbSet<tb_Perfil> tb_Perfil { get; set; }
        public virtual DbSet<tb_subMenu> tb_subMenu { get; set; }
        public virtual DbSet<tb_usuario> tb_usuario { get; set; }
    
        public virtual int sp_BuscaUsuario(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BuscaUsuario", idParameter);
        }
    
        public virtual int sp_EliminaUsuario(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaUsuario", idParameter);
        }
    
        public virtual ObjectResult<sp_equipoxparticipante_Result> sp_equipoxparticipante(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_equipoxparticipante_Result>("sp_equipoxparticipante", idParameter);
        }
    
        public virtual ObjectResult<sp_listaEquipos_Result> sp_listaEquipos(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listaEquipos_Result>("sp_listaEquipos", idParameter);
        }
    
        public virtual ObjectResult<sp_listaModalidades_Result> sp_listaModalidades(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listaModalidades_Result>("sp_listaModalidades", idParameter);
        }
    
        public virtual ObjectResult<sp_listaParticipantexEquipo_Result> sp_listaParticipantexEquipo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listaParticipantexEquipo_Result>("sp_listaParticipantexEquipo", idParameter);
        }
    
        public virtual ObjectResult<sp_ListarDisciplinas_Result> sp_ListarDisciplinas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarDisciplinas_Result>("sp_ListarDisciplinas");
        }
    
        public virtual ObjectResult<sp_ListarEventos_Result> sp_ListarEventos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarEventos_Result>("sp_ListarEventos");
        }
    
        public virtual ObjectResult<sp_listarparticipantes_Result> sp_listarparticipantes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listarparticipantes_Result>("sp_listarparticipantes");
        }
    
        public virtual int sp_listaUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_listaUsuarios");
        }
    
        public virtual ObjectResult<sp_login_Result> sp_login(string login, string clave)
        {
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_login_Result>("sp_login", loginParameter, claveParameter);
        }
    
        public virtual ObjectResult<sp_Participanteinfo_Result> sp_Participanteinfo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Participanteinfo_Result>("sp_Participanteinfo", idParameter);
        }
    
        public virtual int sp_RegistrarUsuarios(Nullable<int> id, string login, string contraseña, Nullable<int> idrol)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("contraseña", contraseña) :
                new ObjectParameter("contraseña", typeof(string));
    
            var idrolParameter = idrol.HasValue ?
                new ObjectParameter("idrol", idrol) :
                new ObjectParameter("idrol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistrarUsuarios", idParameter, loginParameter, contraseñaParameter, idrolParameter);
        }
    }
}
