//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDCibertecAppWebApiRest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventoDeportivoCibertecEntities : DbContext
    {
        public EventoDeportivoCibertecEntities()
            : base("name=EventoDeportivoCibertecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<enlace> enlaces { get; set; }
        public virtual DbSet<rol> rols { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }

        public System.Data.Entity.DbSet<EDCibertecAppWebApiRest.Models.Usuario> Usuarios { get; set; }
    }
}
