//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDCibertecAppWebApiRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_comprobante_pago
    {
        public int id_comprobante_pago { get; set; }
        public System.DateTime fecha { get; set; }
        public int num_ficha { get; set; }
        public string estado { get; set; }
    
        public virtual tb_ficha_inscripcion tb_ficha_inscripcion { get; set; }
    }
}
