//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDCibertecAppWebApiRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_detalle_modalidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_detalle_modalidad()
        {
            this.tb_ficha_inscripcion = new HashSet<tb_ficha_inscripcion>();
        }
    
        public int id_evento { get; set; }
        public int id_modalidad { get; set; }
        public Nullable<int> num_hombres { get; set; }
        public Nullable<int> num_mujeres { get; set; }
        public Nullable<int> cant_max_equipos { get; set; }
    
        public virtual tb_evento tb_evento { get; set; }
        public virtual tb_modalidad tb_modalidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ficha_inscripcion> tb_ficha_inscripcion { get; set; }
    }
}
