//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDCibertecAppWebApiRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario
    {
        public int idUsuario { get; set; }
        public string login { get; set; }
        public string clave { get; set; }
        public int id_Perfil { get; set; }
        public int id_participante { get; set; }
    
        public virtual tb_participante tb_participante { get; set; }
        public virtual tb_Perfil tb_Perfil { get; set; }
    }
}
